In [1]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [2]:
complete_df = pd.read_csv('./dataset/data_complete.csv')
training_df = pd.read_csv('./dataset/training.csv')
testing_df = pd.read_csv('./dataset/testing.csv')

In [4]:
complete_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
dtype: object

In [5]:
training_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
NSM              int64
WeekStatus      object
Day_of_week     object
dtype: object

In [6]:
testing_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
NSM              int64
WeekStatus      object
Day_of_week     object
dtype: object

In [16]:
numeric_data_complete = complete_df.select_dtypes(include=['float64','int64'])
categorical_columns_complete = complete_df.select_dtypes(include=['object'])

### Standardization

In [37]:
#Method_1
#
#numeric_data_complete
complete = np.array(numeric_data_complete)
# calculate mean  
complete_mean = complete.mean(axis=0)  
# calculate variance   
complete_std = complete.std(axis=0)  
# standardize  
complete1 = (complete-complete_mean)/complete_std  
# use function preprocessing.scale to standardize 
complete_scale = preprocessing.scale(complete) 

In [38]:
complete_scale

array([[-0.36767572,  3.30126384, -1.11864475, ...,  0.3669753 ,
        -0.80797358, -0.80797358],
       [-0.36767572,  3.30126384, -1.11864475, ...,  0.34313479,
        -0.44024015, -0.44024015],
       [-0.46521548,  3.30126384, -1.11864475, ...,  0.31929428,
         0.25210868,  0.25210868],
       ...,
       [ 1.68065927,  0.78103476,  2.37445166, ...,  2.26626907,
         0.29049435,  0.29049435],
       [ 3.14375569,  0.78103476,  2.37445166, ...,  2.25832223,
        -1.28759013, -1.28759013],
       [ 3.24129545,  0.78103476,  2.37445166, ...,  2.2503754 ,
         0.6298737 ,  0.6298737 ]])

In [40]:
#Method_2
X = np.array(numeric_data_complete)  
scaler = preprocessing.StandardScaler()  
X_scaled = scaler.fit_transform(X)

In [41]:
X_scaled

array([[-0.36767572,  3.30126384, -1.11864475, ...,  0.3669753 ,
        -0.80797358, -0.80797358],
       [-0.36767572,  3.30126384, -1.11864475, ...,  0.34313479,
        -0.44024015, -0.44024015],
       [-0.46521548,  3.30126384, -1.11864475, ...,  0.31929428,
         0.25210868,  0.25210868],
       ...,
       [ 1.68065927,  0.78103476,  2.37445166, ...,  2.26626907,
         0.29049435,  0.29049435],
       [ 3.14375569,  0.78103476,  2.37445166, ...,  2.25832223,
        -1.28759013, -1.28759013],
       [ 3.24129545,  0.78103476,  2.37445166, ...,  2.2503754 ,
         0.6298737 ,  0.6298737 ]])

### Scaling features to a range

In [45]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=( -1, 1))
complete_minmax = min_max_scaler.fit_transform(complete)

In [46]:
complete_minmax

array([[-0.90654206, -0.14285714, -0.34530095, ...,  0.07692308,
        -0.46910219, -0.46910219],
       [-0.90654206, -0.14285714, -0.34530095, ...,  0.0678733 ,
        -0.25583421, -0.25583421],
       [-0.92523364, -0.14285714, -0.34530095, ...,  0.05882353,
         0.14569532,  0.14569532],
       ...,
       [-0.51401869, -0.71428571,  0.83949314, ...,  0.79788839,
         0.16795719,  0.16795719],
       [-0.23364486, -0.71428571,  0.83949314, ...,  0.79487179,
        -0.74725708, -0.74725708],
       [-0.21495327, -0.71428571,  0.83949314, ...,  0.7918552 ,
         0.36478114,  0.36478114]])

### Normalization

In [48]:
#Method_1
complete_normalized = preprocessing.normalize(complete, norm='l2')

In [49]:
complete_normalized

array([[0.07858774, 0.03929387, 0.02605184, ..., 0.00694192, 0.01738811,
        0.01738811],
       [0.07859288, 0.03929644, 0.02605354, ..., 0.00681138, 0.02437191,
        0.02437191],
       [0.06553308, 0.03931985, 0.02606906, ..., 0.00668437, 0.03754084,
        0.03754084],
       ...,
       [0.32931037, 0.01219668, 0.03110154, ..., 0.01618093, 0.03561323,
        0.03561323],
       [0.47736441, 0.01136582, 0.02898284, ..., 0.01504077, 0.00718636,
        0.00718636],
       [0.48538035, 0.01128792, 0.02878418, ..., 0.01490005, 0.03851307,
        0.03851307]])

In [52]:
#Method_2
normalizer = preprocessing.Normalizer().fit(complete)  # fit does nothing 

In [53]:
normalizer

Normalizer(copy=True, norm='l2')

In [54]:
normalizer.transform(complete)

array([[0.07858774, 0.03929387, 0.02605184, ..., 0.00694192, 0.01738811,
        0.01738811],
       [0.07859288, 0.03929644, 0.02605354, ..., 0.00681138, 0.02437191,
        0.02437191],
       [0.06553308, 0.03931985, 0.02606906, ..., 0.00668437, 0.03754084,
        0.03754084],
       ...,
       [0.32931037, 0.01219668, 0.03110154, ..., 0.01618093, 0.03561323,
        0.03561323],
       [0.47736441, 0.01136582, 0.02898284, ..., 0.01504077, 0.00718636,
        0.00718636],
       [0.48538035, 0.01128792, 0.02878418, ..., 0.01490005, 0.03851307,
        0.03851307]])

Binarization

In [77]:
training_df['WeekStatus_Binarization'] = ''

In [78]:
training_df

date  Appliances  lights         T1       RH_1  \
0      2016-01-11 17:00:00          60      30  19.890000  47.596667   
1      2016-01-11 17:10:00          60      30  19.890000  46.693333   
2      2016-01-11 17:20:00          50      30  19.890000  46.300000   
3      2016-01-11 17:40:00          60      40  19.890000  46.333333   
4      2016-01-11 17:50:00          50      40  19.890000  46.026667   
5      2016-01-11 18:10:00          60      50  19.856667  45.560000   
6      2016-01-11 18:20:00          60      40  19.790000  45.597500   
7      2016-01-11 18:30:00          70      40  19.856667  46.090000   
8      2016-01-11 19:00:00         430      50  20.133333  48.000000   
9      2016-01-11 19:10:00         250      40  20.260000  52.726667   
10     2016-01-11 19:20:00         100      10  20.426667  55.893333   
11     2016-01-11 19:40:00          90      10  20.730000  52.660000   
12     2016-01-11 20:00:00          80      30  20.890000  51.193333   
13     2016-01-11 20:10:00         140      40  20.890000  49.800000   
14     2016-01-11 20:20:00         120      20  20.890000  48.433333   
15     2016-01-11 20:50:00         110      40  21.100000  46.596667   
16     2016-01-11 21:00:00         110      30  21.133333  46.060000   
17     2016-01-11 21:10:00         110      20  21.200000  45.800000   
18     2016-01-11 21:20:00         100      30  21.290000  45.900000   
19     2016-01-11 21:40:00         100      20  21.390000  45.690000   
20     2016-01-11 21:50:00         100      20  21.500000  45.333333   
21     2016-01-11 22:00:00         110      20  21.500000  45.126667   
22     2016-01-11 22:10:00         400      20  21.533333  44.966667   
23     2016-01-11 22:20:00         400      20  21.600000  44.766667   
24     2016-01-11 22:30:00         390      30  21.600000  44.560000   
25     2016-01-11 22:40:00         240      20  21.600000  44.360000   
26     2016-01-11 23:00:00          60      20  21.600000  44.200000   
27     2016-01-11 23:10:00          60      20  21.600000  44.200000   
28     2016-01-11 23:20:00          50      10  21.600000  44.200000   
29     2016-01-11 23:30:00          70      20  21.500000  44.230000   
...                    ...         ...     ...        ...        ...   
14773  2016-05-27 12:20:00         230       0  24.760000  47.926667   
14774  2016-05-27 12:30:00         220       0  24.823333  47.790000   
14775  2016-05-27 12:40:00          90       0  24.890000  47.790000   
14776  2016-05-27 12:50:00          70       0  24.890000  47.790000   
14777  2016-05-27 13:00:00         370       0  24.890000  47.730000   
14778  2016-05-27 13:10:00         280       0  25.033333  48.363333   
14779  2016-05-27 13:20:00         240       0  25.166667  48.156667   
14780  2016-05-27 13:30:00         250       0  25.323333  47.930000   
14781  2016-05-27 13:40:00         220       0  25.390000  47.656667   
14782  2016-05-27 14:00:00         190      10  25.500000  47.060000   
14783  2016-05-27 14:10:00         160       0  25.600000  46.990000   
14784  2016-05-27 14:20:00          80       0  25.600000  46.730000   
14785  2016-05-27 14:40:00          60       0  25.500000  46.360000   
14786  2016-05-27 14:50:00          60       0  25.500000  46.060000   
14787  2016-05-27 15:00:00          60       0  25.500000  45.933333   
14788  2016-05-27 15:10:00          70       0  25.500000  45.760000   
14789  2016-05-27 15:20:00          80       0  25.500000  45.626667   
14790  2016-05-27 15:30:00          80       0  25.500000  45.590000   
14791  2016-05-27 15:40:00          70       0  25.500000  45.522500   
14792  2016-05-27 16:00:00         100       0  25.500000  45.730000   
14793  2016-05-27 16:10:00          90       0  25.500000  45.790000   
14794  2016-05-27 16:20:00         100       0  25.500000  45.933333   
14795  2016-05-27 16:30:00         220       0  25.426667  46.060000   
14796  2016-05-27 16:40:00         180       0  25.500000  46.

In [ ]:
fol row in training_df.rows:
    

In [84]:
training_df.rows

AttributeError: 'DataFrame' object has no attribute 'rows'