In [1]:
from sklearn import preprocessing
import pandas as pd
import numpy as np

In [2]:
complete_df = pd.read_csv('./dataset/data_complete.csv')
training_df = pd.read_csv('./dataset/training.csv')
testing_df = pd.read_csv('./dataset/testing.csv')

In [4]:
complete_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
dtype: object

In [5]:
training_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
NSM              int64
WeekStatus      object
Day_of_week     object
dtype: object

In [6]:
testing_df.dtypes

date            object
Appliances       int64
lights           int64
T1             float64
RH_1           float64
T2             float64
RH_2           float64
T3             float64
RH_3           float64
T4             float64
RH_4           float64
T5             float64
RH_5           float64
T6             float64
RH_6           float64
T7             float64
RH_7           float64
T8             float64
RH_8           float64
T9             float64
RH_9           float64
T_out          float64
Press_mm_hg    float64
RH_out         float64
Windspeed      float64
Visibility     float64
Tdewpoint      float64
rv1            float64
rv2            float64
NSM              int64
WeekStatus      object
Day_of_week     object
dtype: object

In [16]:
numeric_data_complete = complete_df.select_dtypes(include=['float64','int64'])
categorical_columns_complete = complete_df.select_dtypes(include=['object'])

Standardization

In [37]:
#Method_1
#
#numeric_data_complete
complete = np.array(numeric_data_complete)
# calculate mean  
complete_mean = complete.mean(axis=0)  
# calculate variance   
complete_std = complete.std(axis=0)  
# standardize  
complete1 = (complete-complete_mean)/complete_std  
# use function preprocessing.scale to standardize 
complete_scale = preprocessing.scale(complete) 

In [38]:
complete_scale

array([[-0.36767572,  3.30126384, -1.11864475, ...,  0.3669753 ,
        -0.80797358, -0.80797358],
       [-0.36767572,  3.30126384, -1.11864475, ...,  0.34313479,
        -0.44024015, -0.44024015],
       [-0.46521548,  3.30126384, -1.11864475, ...,  0.31929428,
         0.25210868,  0.25210868],
       ...,
       [ 1.68065927,  0.78103476,  2.37445166, ...,  2.26626907,
         0.29049435,  0.29049435],
       [ 3.14375569,  0.78103476,  2.37445166, ...,  2.25832223,
        -1.28759013, -1.28759013],
       [ 3.24129545,  0.78103476,  2.37445166, ...,  2.2503754 ,
         0.6298737 ,  0.6298737 ]])

In [40]:
#Method_2
X = np.array(numeric_data_complete)  
scaler = preprocessing.StandardScaler()  
X_scaled = scaler.fit_transform(X)

In [41]:
X_scaled

array([[-0.36767572,  3.30126384, -1.11864475, ...,  0.3669753 ,
        -0.80797358, -0.80797358],
       [-0.36767572,  3.30126384, -1.11864475, ...,  0.34313479,
        -0.44024015, -0.44024015],
       [-0.46521548,  3.30126384, -1.11864475, ...,  0.31929428,
         0.25210868,  0.25210868],
       ...,
       [ 1.68065927,  0.78103476,  2.37445166, ...,  2.26626907,
         0.29049435,  0.29049435],
       [ 3.14375569,  0.78103476,  2.37445166, ...,  2.25832223,
        -1.28759013, -1.28759013],
       [ 3.24129545,  0.78103476,  2.37445166, ...,  2.2503754 ,
         0.6298737 ,  0.6298737 ]])

Scaling features to a range

In [45]:
min_max_scaler = preprocessing.MinMaxScaler(feature_range=( -1, 1))
complete_minmax = min_max_scaler.fit_transform(complete)

In [46]:
complete_minmax

array([[-0.90654206, -0.14285714, -0.34530095, ...,  0.07692308,
        -0.46910219, -0.46910219],
       [-0.90654206, -0.14285714, -0.34530095, ...,  0.0678733 ,
        -0.25583421, -0.25583421],
       [-0.92523364, -0.14285714, -0.34530095, ...,  0.05882353,
         0.14569532,  0.14569532],
       ...,
       [-0.51401869, -0.71428571,  0.83949314, ...,  0.79788839,
         0.16795719,  0.16795719],
       [-0.23364486, -0.71428571,  0.83949314, ...,  0.79487179,
        -0.74725708, -0.74725708],
       [-0.21495327, -0.71428571,  0.83949314, ...,  0.7918552 ,
         0.36478114,  0.36478114]])

Normalization

In [48]:
#Method_1
complete_normalized = preprocessing.normalize(complete, norm='l2')

In [49]:
complete_normalized

array([[0.07858774, 0.03929387, 0.02605184, ..., 0.00694192, 0.01738811,
        0.01738811],
       [0.07859288, 0.03929644, 0.02605354, ..., 0.00681138, 0.02437191,
        0.02437191],
       [0.06553308, 0.03931985, 0.02606906, ..., 0.00668437, 0.03754084,
        0.03754084],
       ...,
       [0.32931037, 0.01219668, 0.03110154, ..., 0.01618093, 0.03561323,
        0.03561323],
       [0.47736441, 0.01136582, 0.02898284, ..., 0.01504077, 0.00718636,
        0.00718636],
       [0.48538035, 0.01128792, 0.02878418, ..., 0.01490005, 0.03851307,
        0.03851307]])

In [52]:
#Method_2
normalizer = preprocessing.Normalizer().fit(complete)  # fit does nothing 

In [53]:
normalizer

Normalizer(copy=True, norm='l2')

In [54]:
normalizer.transform(complete)

array([[0.07858774, 0.03929387, 0.02605184, ..., 0.00694192, 0.01738811,
        0.01738811],
       [0.07859288, 0.03929644, 0.02605354, ..., 0.00681138, 0.02437191,
        0.02437191],
       [0.06553308, 0.03931985, 0.02606906, ..., 0.00668437, 0.03754084,
        0.03754084],
       ...,
       [0.32931037, 0.01219668, 0.03110154, ..., 0.01618093, 0.03561323,
        0.03561323],
       [0.47736441, 0.01136582, 0.02898284, ..., 0.01504077, 0.00718636,
        0.00718636],
       [0.48538035, 0.01128792, 0.02878418, ..., 0.01490005, 0.03851307,
        0.03851307]])